services:
  autosqlpackage:
    image: ediwang.azurecr.io/autosqlpackage
    container_name: autosqlpackage
    restart: unless-stopped
    volumes:
      - ./config.yaml:/etc/autosqlpackage/config.yaml:ro
      - ./backups:/backups
